name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python --version
      - uses: GuillaumeFalourd/assert-command-line-output@v2.2
        with:
          command_line: python Python/ex3.py
          contains: "[1, 2, 3, 4, 5, 6, 12]"
          expected_result: PASSED