name: ci checks
on:
  push:
    paths: 'Python/**'
jobs:
  python_validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: "test_ex3.py"
        run: |
            OUTPUT=$(python Python/ex3.py)
            if [ "$OUTPUT" != "[1, 2, 3, 4, 5, 6, 12]" ]; then
              echo "Wrong output for ex3.py"
              exit 1
            fi