name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python --version
      - run: |
            OUTPUT=$(python Python/ex3.py)
            if [ $OUTPUT != "[1, 2, 3, 4, 5, 6, 12]" ]; THEN
              echo "Wrong output for ex3.py"
              EXIT -1
            fi